### ISSUE TITLE
Wrong pattern match syntax

### ISSUE THREAD

**Issue by zsluedem** [fabcotech/rholangcheatsheet#4]
In https://fabcotech.github.io/rholangcheatsheet/

Logical `And` and `Or` is wrong.

![image](https://user-images.githubusercontent.com/13496262/164368046-eb0233e8-e95c-4451-ae25-72a406999c75.png)

It should be `@{x /\ 100}` in Logical And
It should be `@"age"!(21 \/ 22)`

**Comment by fabcotech** [comment]
Fixed, it was an issue with the anti-slash
